server:
  port: 8083

spring:
  application:
    name: credit-engine-service
  datasource:
    url: jdbc:postgresql://localhost:5432/los_db
    username: los_user
    password: los_password
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.los.credit: DEBUG
