spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/los_db
    username: los_user
    password: los_password
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    com.los.customer: INFO
